[package]
name = "icon-processor"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
roxmltree = "0.20"
walkdir = "2.5"
regex = "1.10"
